[error] scala.MatchError: null
[error] 	at io.circe.Encoder$$anon$22.apply(Encoder.scala:321)
[error] 	at io.circe.Encoder$$anon$22.apply(Encoder.scala:320)
[error] 	at io.circe.syntax.package$EncoderOps$.asJson$extension(package.scala:8)
[error] 	at Main$.Main$$$anonfun$autorEncoder$1(Main.scala:66)
[error] 	at Main$$anonfun$1.apply(Main.scala:64)
[error] 	at Main$$anonfun$1.apply(Main.scala:64)
[error] 	at io.circe.syntax.package$EncoderOps$.asJson$extension(package.scala:8)
[error] 	at Main$.delayedEndpoint$Main$1(Main.scala:76)
[error] 	at Main$delayedInit$body.apply(Main.scala:6)
[error] 	at scala.Function0.apply$mcV$sp(Function0.scala:42)
[error] 	at scala.Function0.apply$mcV$sp$(Function0.scala:42)
[error] 	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
[error] 	at scala.App.$anonfun$main$1(App.scala:98)
[error] 	at scala.App.$anonfun$main$1$adapted(App.scala:98)
[error] 	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:576)
[error] 	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:574)
[error] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:933)
[error] 	at scala.App.main(App.scala:98)
[error] 	at scala.App.main$(App.scala:96)
[error] 	at Main$.main(Main.scala:6)
[error] 	at Main.main(Main.scala)
[error] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[error] 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[error] 	at sbt.Run.invokeMain(Run.scala:143)
[error] 	at sbt.Run.execute$1(Run.scala:93)
[error] 	at sbt.Run.$anonfun$runWithLoader$5(Run.scala:120)
[error] 	at sbt.Run$.executeSuccess(Run.scala:186)
[error] 	at sbt.Run.runWithLoader(Run.scala:120)
[error] 	at sbt.Defaults$.$anonfun$bgRunTask$6(Defaults.scala:1980)
[error] 	at sbt.Defaults$.$anonfun$termWrapper$2(Defaults.scala:1919)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] 	at scala.util.Try$.apply(Try.scala:213)
[error] 	at sbt.internal.BackgroundThreadPool$BackgroundRunnable.run(DefaultBackgroundJobService.scala:366)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[error] 	at java.base/java.lang.Thread.run(Thread.java:1589)
[error] (Compile / run) scala.MatchError: null
